### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by kangpaidjo** [matiboux/env-converter#9]
1. git clone
2. docker-compose up --build -d
3. container running well

but not work browser ip container?

**Comment by kangpaidjo** [comment]
thanks you

**Comment by matiboux** [comment]
Hello, the steps you described should work well.

After running `docker compose up --build -d`, `docker compose ps` should show:
```
NAME                  IMAGE                      COMMAND                  SERVICE   CREATED          STATUS          PORTS
env-converter-app-1   env-converter-dev:latest   "docker-entrypoint.s…"   app       30 seconds ago   Up 25 seconds   0.0.0.0:80->80/tcp, :::80->80/tcp
```
And the application should be available on http://localhost after starting up.

Make sure your docker has permission to expose the container on the privileged port `80`.
Otherwise, you might need to edit the `.env` file and add this line:
```
HTTP_PORT=8080
```
to change the exposed port. Then after a container restart, you should be able to access the app on http://localhost:8080.
